version: '2'
services:
  web:
    build: .
    volumes:
     - ./:/app
    ports:
     - "3000:3000"    
    environment:
     - NODE_ENV=production     
    links:
     - mongo
    depends_on:
     - mongo  
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"    