version: '2'
services:
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "8443:8443"
    environment:
     - NODE_ENV=production
     - MONGO_DB_URL=mongodb://example:example@ds053312.mongolab.com:53312/todolist     
    volumes_from:
     - web-data
  web-data:
    build:
     context: .
     dockerfile: Dockerfile
    entrypoint: /bin/true
    volumes:
     - /opt/app
     - /opt/app/node_modules
     - /opt/app/client     
 

